[project]
name = "discrete-simulation"
version = "0.1.0"
description = "Notes on discrete event simulation using SimPy"
readme = "README.md"
requires-python = ">=3.9"
dependencies = ["simpy>=4.1.0", "jupyter>=1.0.0", "nbconvert>=7.0.0"]

[tool.uv]
